In [2]:
import numpy as np

In [3]:
new_array=np.array([1,2,3])

In [4]:
new_array2=np.array([[1,2,3],[4,5,6]])

In [5]:
print(new_array)

[1 2 3]


In [6]:
print(new_array2)

[[1 2 3]
 [4 5 6]]


In [7]:
value=np.random.random()
print(value)

0.3953509750219406


In [8]:
array=np.random.random((2,2))
print(array)

[[0.63264411 0.0627756 ]
 [0.15356248 0.17642681]]


In [9]:
array=np.random.randint(2, 10, size=(2,4))
print(array)

[[4 5 4 2]
 [6 3 2 3]]


In [10]:
array=np.zeros(3)
print(array)

[0. 0. 0.]


In [11]:
array=np.full(3, 5)
print(array)

[5 5 5]


In [12]:
array=np.eye(4)
print(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
array=np.ones(5)
print(array)

[1. 1. 1. 1. 1.]


In [14]:
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)

In [15]:
A=np.add(x, y)

In [16]:
A

array([[ 6.,  8.],
       [10., 12.]])

In [17]:
B=x+y

In [18]:
B

array([[ 6.,  8.],
       [10., 12.]])

In [19]:
Z=np.subtract(x, y)

In [20]:
Z

array([[-4., -4.],
       [-4., -4.]])

In [21]:
Y=x-y

In [22]:
Y

array([[-4., -4.],
       [-4., -4.]])

In [23]:
a=np.array([1, 2, 3, 4, 5])
b=np.array([5,7, 13])

In [24]:
#question 1 :

column = int(input("entrer le nombre de column : "))

array = np.random.randint(0, 10, size=(column))

liste = array.tolist() 

entrer le nombre de column : 


ValueError: invalid literal for int() with base 10: ''

In [25]:
liste

NameError: name 'liste' is not defined

In [26]:
#question 2 :

column = int(input("entrer le nombre de column : "))
ligne = int(input("entrer le nombre de ligne : "))


array = np.random.randint(0, 10, size=(ligne , column))

print(array)

print(array.trace())

entrer le nombre de column : 


ValueError: invalid literal for int() with base 10: ''

In [28]:
#question 3 :

column = int(input("entrer le nombre de column : "))
ligne = int(input("entrer le nombre de ligne : "))


array = np.random.randint(0, 10, size=(ligne , column))

x = int (input("entrer le valeur de x : "))
liste = []

for i in range (ligne) :
    for j in range (column) : 
        if array[i,j] > x :
            liste.append(array[i,j])

entrer le nombre de column : 5
entrer le nombre de ligne : 4
entrer le valeur de x : 1


In [29]:
liste

[4, 9, 5, 4, 5, 8, 2, 9, 2, 7, 3, 2, 5, 5]

In [30]:
#question 4 : 

#Given two arrays, A & B have the same shape. 
#The task is to apply addition by hand: C is the new array. 

A = np.random.randint(0, 10, size=(5 , 5))
B = np.random.randint(0, 10, size=(5 , 5))

C = np.add(A,B)

In [35]:
C

array([[15,  3, 16,  5,  9],
       [ 8, 15, 11, 11,  7],
       [ 6, 13,  5,  1,  6],
       [ 6, 13,  5, 11,  5],
       [13,  9, 18,  9,  3]])

In [36]:
C.mean(axis=0)

array([ 9.6, 10.6, 11. ,  7.4,  6. ])

In [43]:
#question 5 :

#Write a NumPy program to subtract the mean of each row of a given matrix.
#Hint: use the mean function

column = int(input("entrer le nombre de column : "))
ligne = int(input("entrer le nombre de ligne : "))

array = np.random.randint(0, 10, size=(ligne , column))
a = array.mean(axis=0)

print(a)
print(array)
print(array - a)


entrer le nombre de column : 5
entrer le nombre de ligne : 4
[3.25 3.25 4.25 5.   4.  ]
[[0 0 9 6 9]
 [8 8 7 3 3]
 [0 4 0 8 2]
 [5 1 1 3 2]]
[[-3.25 -3.25  4.75  1.    5.  ]
 [ 4.75  4.75  2.75 -2.   -1.  ]
 [-3.25  0.75 -4.25  3.   -2.  ]
 [ 1.75 -2.25 -3.25 -2.   -2.  ]]
